minhas_paralavras_de_parada = [
    "able",
    "about",
    "above",
    "abst",
    "accordance",
    "according",
    "accordingly",
    "across",
    "act",
    "actually",
    "added",
    "adj",
    "affected",
    "affecting",
    "affects",
    "after",
    "afterwards",
    "again",
    "against",
    "ah",
    "all",
    "almost",
    "alone",
    "along",
    "already",
    "also",
    "although",
    "always",
    "am",
    "among",
    "amongst",
    "an",
    "and",
    "announce",
    "another",
    "any",
    "anybody",
    "anyhow",
    "anymore",
    "anyone",
    "anything",
    "anyway",
    "anyways",
    "anywhere",
    "apparently",
    "approximately",
    "are",
    "aren",
    "arent",
    "arise",
    "around",
    "as",
    "aside",
    "ask",
    "asking",
    "at",
    "auth",
    "available",
    "away",
    "awfully",
    "b",
    "back",
    "be",
    "became",
    "because",
    "become",
    "becomes",
    "becoming",
    "been",
    "before",
    "beforehand",
    "begin",
    "beginning",
    "beginnings",
    "begins",
    "behind",
    "being",
    "believe",
    "below",
    "beside",
    "besides",
    "between",
    "beyond",
    "biol",
    "both",
    "brief",
    "briefly",
    "but",
    "by",
    "c",
    "ca",
    "came",
    "can",
    "cannot",
    "cant",
    "cause",
    "causes",
    "certain",
    "certainly",
    "co",
    "com",
    "come",
    "comes",
    "contain",
    "containing",
    "contains",
    "could",
    "couldnt",
    "d",
    "date",
    "did",
    "didnt",
    "different",
    "do",
    "does",
    "doesnt",
    "doing",
    "done",
    "dont",
    "down",
    "downwards",
    "due",
    "during",
    "e",
    "each",
    "ed",
    "edu",
    "effect",
    "eg",
    "eight",
    "eighty",
    "either",
    "else",
    "elsewhere",
    "end",
    "ending",
    "enough",
    "especially",
    "et",
    "etc",
    "even",
    "ever",
    "every",
    "everybody",
    "everyone",
    "everything",
    "everywhere",
    "ex",
    "except",
    "f",
    "far",
    "few",
    "ff",
    "fifth",
    "first",
    "five",
    "fix",
    "followed",
    "following",
    "follows",
    "for",
    "former",
    "formerly",
    "forth",
    "found",
    "four",
    "from",
    "further",
    "furthermore",
    "g",
    "gave",
    "get",
    "gets",
    "getting",
    "give",
    "given",
    "gives",
    "giving",
    "go",
    "goes",
    "gone",
    "got",
    "gotten",
    "h",
    "had",
    "happens",
    "hardly",
    "has",
    "hasnt",
    "have",
    "havent",
    "having",
    "he",
    "hed",
    "hence",
    "her",
    "here",
    "hereafter",
    "hereby",
    "herein",
    "heres",
    "hereupon",
    "hers",
    "herself",
    "hes",
    "hi",
    "hid",
    "him",
    "himself",
    "his",
    "hither",
    "home",
    "how",
    "howbeit",
    "however",
    "hundred",
    "i",
    "id",
    "ie",
    "if",
    "im",
    "immediate",
    "immediately",
    "importance",
    "important",
    "in",
    "inc",
    "indeed",
    "index",
    "information",
    "instead",
    "into",
    "invention",
    "inward",
    "is",
    "isnt",
    "it",
    "itd",
    "its",
    "itself",
    "j",
    "just",
    "k",
    "keep",
    "kept",
    "kg",
    "km",
    "know",
    "known",
    "knows",
    "l",
    "largely",
    "last",
    "lately",
    "later",
    "latter",
    "latterly",
    "least",
    "less",
    "lest",
    "let",
    "lets",
    "like",
    "liked",
    "likely",
    "line",
    "little",
    "ll",
    "look",
    "looking",
    "looks",
    "ltd",
    "m",
    "made",
    "mainly",
    "make",
    "makes",
    "many",
    "may",
    "maybe",
    "me",
    "mean",
    "means",
    "meantime",
    "meanwhile",
    "merely",
    "mg",
    "might",
    "million",
    "miss",
    "ml",
    "more",
    "moreover",
    "most",
    "mostly",
    "mr",
    "mrs",
    "much",
    "mug",
    "must",
    "my",
    "myself",
    "n",
    "na",
    "name",
    "namely",
    "nay",
    "nd",
    "near",
    "nearly",
    "necessarily",
    "necessary",
    "need",
    "needs",
    "neither",
    "never",
    "nevertheless",
    "new",
    "next",
    "nine",
    "ninety",
    "no",
    "nobody",
    "non",
    "none",
    "nonetheless",
    "noone",
    "nor",
    "normally",
    "nos",
    "not",
    "noted",
    "nothing",
    "now",
    "nowhere",
    "o",
    "obtain",
    "obtained",
    "obviously",
    "of",
    "off",
    "often",
    "oh",
    "ok",
    "okay",
    "old",
    "omitted",
    "on",
    "once",
    "one",
    "ones",
    "only",
    "onto",
    "or",
    "ord",
    "other",
    "others",
    "otherwise",
    "ought",
    "our",
    "ours",
    "ourselves",
    "out",
    "outside",
    "over",
    "overall",
    "owing",
    "own",
    "p",
    "page",
    "pages",
    "part",
    "particular",
    "particularly",
    "past",
    "per",
    "perhaps",
    "placed",
    "please",
    "plus",
    "poorly",
    "possible",
    "possibly",
    "potentially",
    "pp",
    "predominantly",
    "present",
    "previously",
    "primarily",
    "probably",
    "promptly",
    "proud",
    "provides",
    "put",
    "q",
    "que",
    "quickly",
    "quite",
    "qv",
    "ran",
    "rather",
    "rd",
    "re",
    "readily",
    "really",
    "recent",
    "recently",
    "ref",
    "refs",
    "regarding",
    "regardless",
    "regards",
    "related",
    "relatively",
    "research",
    "respectively",
    "resulted",
    "resulting",
    "results",
    "right",
    "run",
    "s",
    "said",
    "same",
    "saw",
    "say",
    "saying",
    "says",
    "sec",
    "section",
    "see",
    "seeing",
    "seem",
    "seemed",
    "seeming",
    "seems",
    "seen",
    "self",
    "selves",
    "sent",
    "seven",
    "several",
    "shall",
    "she",
    "shed",
    "shes",
    "should",
    "show",
    "showed",
    "shown",
    "showns",
    "shows",
    "significant",
    "significantly",
    "similar",
    "similarly",
    "since",
    "six",
    "slightly",
    "so",
    "some",
    "somebody",
    "somehow",
    "someone",
    "somethan",
    "something",
    "sometime",
    "sometimes",
    "somewhat",
    "somewhere",
    "soon",
    "sorry",
    "specifically",
    "specified",
    "specify",
    "specifying",
    "still",
    "stop",
    "strongly",
    "sub",
    "substantially",
    "successfully",
    "such",
    "sufficiently",
    "suggest",
    "sup",
    "take",
    "taken",
    "taking",
    "tell",
    "tends",
    "th",
    "than",
    "thank",
    "thanks",
    "thanx",
    "that",
    "thats",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "thence",
    "there",
    "thereafter",
    "thereby",
    "thered",
    "therefore",
    "therein",
    "thereof",
    "therere",
    "theres",
    "thereto",
    "thereupon",
    "these",
    "they",
    "theyd",
    "theyre",
    "think",
    "this",
    "those",
    "thou",
    "though",
    "thoughh",
    "thousand",
    "throug",
    "through",
    "throughout",
    "thru",
    "thus",
    "til",
    "tip",
    "to",
    "together",
    "too",
    "took",
    "toward",
    "towards",
    "tried",
    "tries",
    "truly",
    "try",
    "trying",
    "ts",
    "twice",
    "two",
    "u",
    "un",
    "under",
    "unfortunately",
    "unless",
    "unlike",
    "unlikely",
    "until",
    "unto",
    "up",
    "upon",
    "ups",
    "us",
    "use",
    "used",
    "useful",
    "usefully",
    "usefulness",
    "uses",
    "using",
    "usually",
    "v",
    "value",
    "various",
    "ve",
    "very",
    "via",
    "viz",
    "vol",
    "vols",
    "vs",
    "w",
    "want",
    "wants",
    "was",
    "wasnt",
    "way",
    "we",
    "wed",
    "welcome",
    "went",
    "were",
    "werent",
    "what",
    "whatever",
    "whats",
    "when",
    "whence",
    "whenever",
    "where",
    "whereafter",
    "whereas",
    "whereby",
    "wherein",
    "wheres",
    "whereupon",
    "wherever",
    "whether",
    "which",
    "while",
    "whim",
    "whither",
    "who",
    "whod",
    "whoever",
    "whole",
    "whom",
    "whomever",
    "whos",
    "whose",
    "why",
    "widely",
    "willing",
    "wish",
    "with",
    "within",
    "without",
    "wont",
    "words",
    "world",
    "would",
    "wouldnt",
    "www",
    "x",
    "y",
    "yes",
    "yet",
    "you",
    "youd",
    "your",
    "youre",
    "yours",
    "yourself",
    "yourselves",
    "z",
    "zero"
]

segunda_lista_stop_words = [
    "able",
    "about",
    "above",
    "abroad",
    "according",
    "accordingly",
    "across",
    "actually",
    "adj",
    "after",
    "afterwards",
    "again",
    "against",
    "ago",
    "ahead",
    "ain't",
    "all",
    "allow",
    "allows",
    "almost",
    "alone",
    "along",
    "alongside",
    "already",
    "also",
    "although",
    "always",
    "am",
    "amid",
    "amidst",
    "among",
    "amongst",
    "an",
    "and",
    "another",
    "any",
    "anybody",
    "anyhow",
    "anyone",
    "anything",
    "anyway",
    "anyways",
    "anywhere",
    "apart",
    "appear",
    "appreciate",
    "appropriate",
    "are",
    "aren't",
    "around",
    "as",
    "a's",
    "aside",
    "ask",
    "asking",
    "associated",
    "at",
    "available",
    "away",
    "awfully",
    "back",
    "backward",
    "backwards",
    "be",
    "became",
    "because",
    "become",
    "becomes",
    "becoming",
    "been",
    "before",
    "beforehand",
    "begin",
    "behind",
    "being",
    "believe",
    "below",
    "beside",
    "besides",
    "best",
    "better",
    "between",
    "beyond",
    "both",
    "brief",
    "but",
    "by",
    "came",
    "can",
    "cannot",
    "cant",
    "can't",
    "caption",
    "cause",
    "causes",
    "certain",
    "certainly",
    "clearly",
    "c'mon",
    "co",
    "co.",
    "com",
    "come",
    "comes",
    "concerning",
    "consequently",
    "consider",
    "considering",
    "contain",
    "containing",
    "contains",
    "corresponding",
    "could",
    "couldn't",
    "course",
    "c's",
    "currently",
    "dare",
    "daren't",
    "definitely",
    "described",
    "despite",
    "did",
    "didn't",
    "different",
    "directly",
    "do",
    "does",
    "doesn't",
    "doing",
    "done",
    "don't",
    "down",
    "downwards",
    "during",
    "each",
    "edu",
    "eg",
    "eight",
    "eighty",
    "either",
    "else",
    "elsewhere",
    "end",
    "ending",
    "enough",
    "entirely",
    "especially",
    "et",
    "etc",
    "even",
    "ever",
    "evermore",
    "every",
    "everybody",
    "everyone",
    "everything",
    "everywhere",
    "ex",
    "exactly",
    "example",
    "except",
    "fairly",
    "far",
    "farther",
    "few",
    "fewer",
    "fifth",
    "first",
    "five",
    "followed",
    "following",
    "follows",
    "for",
    "forever",
    "former",
    "formerly",
    "forth",
    "forward",
    "found",
    "four",
    "from",
    "further",
    "furthermore",
    "get",
    "gets",
    "getting",
    "given",
    "gives",
    "go",
    "goes",
    "going",
    "gone",
    "got",
    "gotten",
    "greetings",
    "had",
    "hadn't",
    "half",
    "happens",
    "hardly",
    "has",
    "hasn't",
    "have",
    "haven't",
    "having",
    "he",
    "he'd",
    "he'll",
    "hello",
    "help",
    "hence",
    "her",
    "here",
    "hereafter",
    "hereby",
    "herein",
    "here's",
    "hereupon",
    "hers",
    "herself",
    "he's",
    "hi",
    "him",
    "himself",
    "his",
    "hither",
    "hopefully",
    "how",
    "howbeit",
    "however",
    "hundred",
    "i'd",
    "ie",
    "if",
    "ignored",
    "i'll",
    "i'm",
    "immediate",
    "in",
    "inasmuch",
    "inc",
    "inc.",
    "indeed",
    "indicate",
    "indicated",
    "indicates",
    "inner",
    "inside",
    "insofar",
    "instead",
    "into",
    "inward",
    "is",
    "isn't",
    "it",
    "it'd",
    "it'll",
    "its",
    "it's",
    "itself",
    "i've",
    "just",
    "k",
    "keep",
    "keeps",
    "kept",
    "know",
    "known",
    "knows",
    "last",
    "lately",
    "later",
    "latter",
    "latterly",
    "least",
    "less",
    "lest",
    "let",
    "let's",
    "like",
    "liked",
    "likely",
    "likewise",
    "little",
    "look",
    "looking",
    "looks",
    "low",
    "lower",
    "ltd",
    "made",
    "mainly",
    "make",
    "makes",
    "many",
    "may",
    "maybe",
    "mayn't",
    "me",
    "mean",
    "meantime",
    "meanwhile",
    "merely",
    "might",
    "mightn't",
    "mine",
    "minus",
    "miss",
    "more",
    "moreover",
    "most",
    "mostly",
    "mr",
    "mrs",
    "much",
    "must",
    "mustn't",
    "my",
    "myself",
    "name",
    "namely",
    "nd",
    "near",
    "nearly",
    "necessary",
    "need",
    "needn't",
    "needs",
    "neither",
    "never",
    "neverf",
    "neverless",
    "nevertheless",
    "new",
    "next",
    "nine",
    "ninety",
    "no",
    "nobody",
    "non",
    "none",
    "nonetheless",
    "noone",
    "no-one",
    "nor",
    "normally",
    "not",
    "nothing",
    "notwithstanding",
    "novel",
    "now",
    "nowhere",
    "obviously",
    "of",
    "off",
    "often",
    "oh",
    "ok",
    "okay",
    "old",
    "on",
    "once",
    "one",
    "ones",
    "one's",
    "only",
    "onto",
    "opposite",
    "or",
    "other",
    "others",
    "otherwise",
    "ought",
    "oughtn't",
    "our",
    "ours",
    "ourselves",
    "out",
    "outside",
    "over",
    "overall",
    "own",
    "particular",
    "particularly",
    "past",
    "per",
    "perhaps",
    "placed",
    "please",
    "plus",
    "possible",
    "presumably",
    "probably",
    "provided",
    "provides",
    "que",
    "quite",
    "qv",
    "rather",
    "rd",
    "re",
    "really",
    "reasonably",
    "recent",
    "recently",
    "regarding",
    "regardless",
    "regards",
    "relatively",
    "respectively",
    "right",
    "round",
    "said",
    "same",
    "saw",
    "say",
    "saying",
    "says",
    "second",
    "secondly",
    "see",
    "seeing",
    "seem",
    "seemed",
    "seeming",
    "seems",
    "seen",
    "self",
    "selves",
    "sensible",
    "sent",
    "serious",
    "seriously",
    "seven",
    "several",
    "shall",
    "shan't",
    "she",
    "she'd",
    "she'll",
    "she's",
    "should",
    "shouldn't",
    "since",
    "six",
    "so",
    "some",
    "somebody",
    "someday",
    "somehow",
    "someone",
    "something",
    "sometime",
    "sometimes",
    "somewhat",
    "somewhere",
    "soon",
    "sorry",
    "specified",
    "specify",
    "specifying",
    "still",
    "sub",
    "such",
    "sup",
    "sure",
    "take",
    "taken",
    "taking",
    "tell",
    "tends",
    "th",
    "than",
    "thank",
    "thanks",
    "thanx",
    "that",
    "that'll",
    "thats",
    "that's",
    "that've",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "thence",
    "there",
    "thereafter",
    "thereby",
    "there'd",
    "therefore",
    "therein",
    "there'll",
    "there're",
    "theres",
    "there's",
    "thereupon",
    "there've",
    "these",
    "they",
    "they'd",
    "they'll",
    "they're",
    "they've",
    "thing",
    "things",
    "think",
    "third",
    "thirty",
    "this",
    "thorough",
    "thoroughly",
    "those",
    "though",
    "three",
    "through",
    "throughout",
    "thru",
    "thus",
    "till",
    "to",
    "together",
    "too",
    "took",
    "toward",
    "towards",
    "tried",
    "tries",
    "truly",
    "try",
    "trying",
    "t's",
    "twice",
    "two",
    "un",
    "under",
    "underneath",
    "undoing",
    "unfortunately",
    "unless",
    "unlike",
    "unlikely",
    "until",
    "unto",
    "up",
    "upon",
    "upwards",
    "us",
    "use",
    "used",
    "useful",
    "uses",
    "using",
    "usually",
    "v",
    "value",
    "various",
    "versus",
    "very",
    "via",
    "viz",
    "vs",
    "want",
    "wants",
    "was",
    "wasn't",
    "way",
    "we",
    "we'd",
    "welcome",
    "well",
    "we'll",
    "went",
    "were",
    "we're",
    "weren't",
    "we've",
    "what",
    "whatever",
    "what'll",
    "what's",
    "what've",
    "when",
    "whence",
    "whenever",
    "where",
    "whereafter",
    "whereas",
    "whereby",
    "wherein",
    "where's",
    "whereupon",
    "wherever",
    "whether",
    "which",
    "whichever",
    "while",
    "whilst",
    "whither",
    "who",
    "who'd",
    "whoever",
    "whole",
    "who'll",
    "whom",
    "whomever",
    "who's",
    "whose",
    "why",
    "will",
    "willing",
    "wish",
    "with",
    "within",
    "without",
    "wonder",
    "won't",
    "would",
    "wouldn't",
    "yes",
    "yet",
    "you",
    "you'd",
    "you'll",
    "your",
    "you're",
    "yours",
    "yourself",
    "yourselves",
    "you've",
    "zero",
    "a",
    "how's",
    "i",
    "when's",
    "why's",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "j",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "uucp",
    "w",
    "x",
    "y",
    "z",
    "I",
    "www",
    "amount",
    "bill",
    "bottom",
    "call",
    "computer",
    "con",
    "couldnt",
    "cry",
    "de",
    "describe",
    "detail",
    "due",
    "eleven",
    "empty",
    "fifteen",
    "fifty",
    "fill",
    "find",
    "fire",
    "forty",
    "front",
    "full",
    "give",
    "hasnt",
    "herse",
    "himse",
    "interest",
    "itse”",
    "mill",
    "move",
    "myse”",
    "part",
    "put",
    "show",
    "side",
    "sincere",
    "sixty",
    "system",
    "ten",
    "thick",
    "thin",
    "top",
    "twelve",
    "twenty",
    "abst",
    "accordance",
    "act",
    "added",
    "adopted",
    "affected",
    "affecting",
    "affects",
    "ah",
    "announce",
    "anymore",
    "apparently",
    "approximately",
    "aren",
    "arent",
    "arise",
    "auth",
    "beginning",
    "beginnings",
    "begins",
    "biol",
    "briefly",
    "ca",
    "date",
    "ed",
    "effect",
    "et-al",
    "ff",
    "fix",
    "gave",
    "giving",
    "heres",
    "hes",
    "hid",
    "home",
    "id",
    "im",
    "immediately",
    "importance",
    "important",
    "index",
    "information",
    "invention",
    "itd",
    "keys",
    "kg",
    "km",
    "largely",
    "lets",
    "line",
    "'ll",
    "means",
    "mg",
    "million",
    "ml",
    "mug",
    "na",
    "nay",
    "necessarily",
    "nos",
    "noted",
    "obtain",
    "obtained",
    "omitted",
    "ord",
    "owing",
    "page",
    "pages",
    "poorly",
    "possibly",
    "potentially",
    "pp",
    "predominantly",
    "present",
    "previously",
    "primarily",
    "promptly",
    "proud",
    "quickly",
    "ran",
    "readily",
    "ref",
    "refs",
    "related",
    "research",
    "resulted",
    "resulting",
    "results",
    "run",
    "sec",
    "section",
    "shed",
    "shes",
    "showed",
    "shown",
    "showns",
    "shows",
    "significant",
    "significantly",
    "similar",
    "similarly",
    "slightly",
    "somethan",
    "specifically",
    "state",
    "states",
    "stop",
    "strongly",
    "substantially",
    "successfully",
    "sufficiently",
    "suggest",
    "thered",
    "thereof",
    "therere",
    "thereto",
    "theyd",
    "theyre",
    "thou",
    "thoughh",
    "thousand",
    "throug",
    "til",
    "tip",
    "ts",
    "ups",
    "usefully",
    "usefulness",
    "'ve",
    "vol",
    "vols",
    "wed",
    "whats",
    "wheres",
    "whim",
    "whod",
    "whos",
    "widely",
    "words",
    "world",
    "youd",
    "youre"
]

lista_tech = [
    "a",
    "e",
    "i",
    "o",
    "u",
    "s",
    "the",
    "to",
    "and",
    "my",
    "is",
    "for",
    "on",
    "of",
    "it",
    "in",
    "new",
    "with",
    "you",
    "me",
    "from",
    "just",
    "at",
    "an",
    "have",
    "your",
    "-",
    "this",
    "has",
    "that",
    "get",
    "now",
    "are",
    "so",
    "do",
    "be",
    "out",
    "i'm",
    "all",
    "will",
    "what",
    "update",
    "store",
    "phone",
    "or",
    "down",
    "when",
    "time",
    "like",
    "it's",
    "why",
    "up",
    "think",
    "the",
    "had",
    "by",
    "was",
    "very",
    "their",
    "than",
    "not",
    "every",
    "but",
    "who",
    #"via",
    #"they",
    #"spotted",
    #"service",
    #"send",
    #"no",
    #"more",
    #"fan",
    #"customer",
    #"been",
    #"apple",
    #"am",
    #"about",
    #"would",
    #"world",
    #"we",
    ##using",
    #"touch",
    #"them",
    #"see",
    #"people",
    #"one",
    #"i've",
    #"if",
    #"hey",
    #"go",
    #"as",
    #"after"
]

lista_airline = [
    "a",
    "e",
    "i",
    "o",
    "u",
    "s",
    "to",
    "the",
    "for",
    "and",
    "you",
    "on",
    "my",
    "in",
    "flight",
    "is",
    "of",
    "me",
    "with",
    "was",
    "at",
    "it",
    "have",
    "from",
    "your",
    "be",
    "that",
    "get",
    "but",
    "are",
    "not",
    "this",
    "can",
    "so",
    "just",
    "-",
    "no",
    "an",
    "we",
    "will",
    "cancelled",
    "&amp",
    "do",
    "out",
    "i'm",
    "been",
    "service",
    "thank",
    "thanks",
    "would",
    "flights",
    "got",
    "flight",
    "customer",
    "time",
    "when",
    "thank",
    "they",
    "our",
    "now",
    "up",
    "thanks",
    "one",
    "there",
    "any",
    "as",
    "all",
    "if",
    "need",
    "fly",
    "has",
    "plane",
    "help",
    "had",
    "about",
    "please",
    "by",
    "what",
    "still",
    "go",
    "back",
    "or",
    "like",
    "us",
    "flying",
    "am",
    "after",
    "you",
    "how",
    "great",
    "you",
    "guys",
    "know",
    "were",
    "hold",
    "love",
    "don't",
    ":)",
    "phone",
    "late",
    "see",
    "new",
    "hours",
    "only",
    "it's",
    "i've",
    "make",
    "gate",
    "why",
    "can't",
    "bag",
    "want",
    "then",
    "first",
    "delayed",
    "you",
    "good",
    "way",
    "more",
    "over",
    "is",
    "home",
    "did",
    "airline",
    "next",
    "even",
    "very",
    "their",
    "hour",
    "who",
    "united",
    "should",
    "last",
    "flight",
    "because",
    "travel",
    "take",
    "no",
    "never",
    "some",
    "i'll",
    "dm",
    "call",
    "best",
    "really",
    # "much",
    # "made",
    # "could",
    # "can",
    # "getting",
    # "flightled",
    # "told",
    # "check",
    # "airport",
    # "wait",
    # "the",
    # "thanks",
    # "other",
    # "my",
    # "just",
    # "how",
    # "destinationdragons",
    # "we",
    # "trip",
    # "waiting",
    # "than",
    # "sent",
    # "now",
    # "it",
    # "crew",
    # "today",
    # "where",
    # "trying",
    # "today",
    # "her",
    # "day",
    # "booking",
    # "any",
    # "tickets",
    # "she",
    # "being",
    # "bags",
    # "use",
    # "through",
    # "since",
    # "problems",
    # "left",
    # "going",
    # "email",
    # "appreciate",
    # "what",
    # "via",
    # "tomorrow",
    # "think",
    # "them",
    # "someone",
    # "off",
    # "number",
    # "due",
    # "your",
    # "weather",
    # "this",
    # "said",
    # "right",
    # "people",
    # "baggage",
    # "thanks",
    # "sure",
    # "seat",
    # "into",
    # "find",
    # "didn't",
    # "book",
    # "better",
    # "able",
    # "work",
    # "that's",
    # "tell",
    # "put",
    # "please",
    # "long",
    # "it",
    # "boarding",
    # "ticket",
    # "passengers",
    # "follow",
    # "chance",
    # "but",
    # "another",
    # "won't",
    # "they",
    # "staff",
    # "pay",
    # "ever",
    # "days",
    # "so",
    # "sitting",
    # "seats",
    # "online",
    # "min",
    # "looking",
    # "jfk",
    # "if",
    # "give",
    # "does",
    # "direct",
    # "agent",
    # "us",
    # "two",
    # "too",
    # "says",
    # "minutes",
    # "it's",
    # "hope",
    # "great",
    # "experience",
    # "delay",
    # "ceo",
    # "and",
    # "taking",
    # "response",
    # "open",
    # "me",
    # "you're",
    # "until",
    # "times",
    # "something",
    # "send",
    # "leave",
    # "here",
    # "free",
    # "credit",
    # "come",
    # "again",
    # "well",
    # "same",
    # "nice",
    # "morning",
    # "having",
    # "forward",
    # "connection",
    # "care",
    # "booked",
    # "before",
    # "bad",
    # "thanks",
    # "not",
    # "miss",
    # "love",
    # "look",
    # "info",
    # "he",
    # "gave",
    # "flighted",
    # "finally",
    # "earlier",
    # "boston",
    # "also",
    # "you",
    # "took",
    # "site",
    # "service",
    # "response",
    # "reservations",
    # "night",
    # "miles",
    # "keep",
    # "its",
    # "flt",
    # "family",
    # "done",
    # "do",
    # "couldn't",
    # "attendant",
    # "already",
    # "add",
    # "when",
    # "wall",
    # "phl",
    # "now",
    # "new",
    # "most",
    # "many",
    # "lost",
    # "link",
    # "let",
    # "job",
    # "few",
    # "charlotte",
    # "can't",
    # "always",
    # "airways",
    # "again",
    # "year",
    # "w/",
    # "update",
    # "tried",
    # "tonight",
    # "time",
    # "those",
    # "that's",
    # "she",
    # "reservation",
    # "rebook",
    # "making",
    # "lax",
    # "instead",
    # "hotel",
    # "flight",
    # "employees",
    # "contact",
    # "confirmation",
    # "class",
    # "business",
    # "bos",
    # "big",
    # "bc",
    # "are",
    # "yes",
    # "will",
    # "which",
    # "vegas",
    # "the",
    # "thanks",
    # "supposed",
    # "stuck",
    # "still",
    # "received",
    # "missed",
    # "might",
    # "i'd",
    # "here",
    # "have",
    # "each",
    # "doing",
    # "different",
    # "customers",
    # "awesome",
    # "amazing",
    # "agents",
    # "yes",
    # "years",
    # "without",
    # "wifi",
    # "why",
    # "while",
    # "website",
    # "show",
    # "sfo",
    # "san",
    # "rebooked",
    # "nashville",
    # "name",
    # "luggage",
    # "it",
    # "full",
    # "down",
    # "company",
    # "clt",
    # "carry",
    # "all",
    # "airlines",
    # "airline",
    # "you",
    # "working",
    # "waited",
    # "that",
    # "sw",
    # "southwest",
    # "return",
    # "once",
    # "offer",
    # "money",
    # "missing",
    # "makes",
    # "jetblue",
    # "issue",
    # "haven't",
    # "happy",
    # "good",
    # "found",
    # "fll",
    # "flightr",
    # "doesn't",
    # "ð",
    # "connecting",
    # "checked",
    # "away",
    # "almost",
    # ":-)",
    # "y'all",
    # "wasn't",
    # "voucher",
    # "using",
    # "that",
    # "stranded",
    # "refund",
    # "pilot",
    # "own",
    # "no",
    # "need",
    # "lot",
    # "looking",
    # "idea",
    # "helpful",
    # "ground",
    # "form",
    # "flight",
    # "extra",
    # "everyone",
    # "every",
    # "during",
    # "departure",
    # "delays",
    # "day",
    # "cost",
    # "called",
    # "birthday",
    # "between",
    # "believe",
    # "are",
    # "actually",
    # "we're",
    # "used",
    # "under",
    # "try",
    # "traveling",
    # "too",
    # "thought",
    # "things",
    # "thing",
    # "start",
    # "sorry",
    # "share",
    # "quick",
    # "problem",
    # "past",
    # "pass",
    # "out",
    # "on",
    # "newark",
    # "needs",
    # "me",
    # "little",
    # "line",
    # "least",
    # "journal",
    # "issues",
    # "in",
    # "hours",
    # "his",
    # "help",
    # "flight",
    # "fix",
    # "feel",
    # "far",
    # "early",
    # "delay",
    # "dc",
    # "claim",
    # "bring",
    # "board",
    # "back",
    # "available",
    # "anything",
    # "3rd",
    # "yet",
    # "yall",
    # "weeks",
    # "wanted",
    # "ur",
    # "updates",
    # "up",
    # "tweeting",
    # "though",
    # "there's",
    # "team",
    # "talk",
    # "such",
    # "street",
    # "stop",
    # "service",
    # "second",
    # "reflight",
    # "real",
    # "plane",
    # "paid",
    # "ord",
    # "old",
    # "off",
    # "nyc",
    # "me",
    # "less",
    # "landing",
    # "it",
    # "isn't",
    # "hoping",
    # "hi",
    # "hear",
    # "half",
    # "had",
    # "guys",
    # "giving",
    # "flown",
    # "flights",
    # "first",
    # "everything",
    # "destination",
    # "denver",
    # "dallas",
    # "customer",
    # "coming",
    # "charge",
    # "changing",
    # "catch",
    # "car",
    # "bna",
    # "been",
    # "bag",
    # "awesome",
    # "atlanta",
    # "app",
    # "anyone",
    # "airport",
    # "yesterday",
    # "wrong",
    # "wouldn't",
    # "with",
    # "whole",
    # "very",
    # "upgrade",
    # "tweet",
    # "trying",
    # "tonight",
    # "tomorrow",
    # "tix",
    # "time",
    # "switch",
    # "super",
    # "status",
    # "standby",
    # "soon",
    # "she's",
    # "say",
    # "safety",
    # "reply",
    # "possible",
    # "poor",
    # "policy",
    # "plus",
    # "planes",
    # "only",
    # "oh",
    # "nothing",
    # "never",
    # "needed",
    # "must",
    # "morning",
    # "mins",
    # "mechanical",
    # "mean",
    # "live",
    # "lack",
    # "kind",
    # "kids",
    # "jetblue",
    # "in",
    # "heard",
    # "hard",
    # "gonna",
    # "given",
    # "friend",
    # "food",
    # "follow",
    # "flight",
    # "end",
    # "else",
    # "drive",
    # "does",
    # "cold",
    # "chicago",
    # "bought",
    # "austin",
    # "air",
    # "would",
    # "worst",
    # "wonderful",
    # "we've",
    # "we're",
    # "went",
    # "way",
    # "united",
    # "twitter",
    # "today",
    # "time",
    # "these",
    # "them",
    # "that",
    # "support",
    # "snow",
    # "service",
    # "scheduled",
    # "saying",
    # "routes",
    # "route",
    # "round",
    # "room",
    # "ready",
    # "question",
    # "prompt",
    # "promo",
    # "points",
    # "person",
    # "paying",
    # "page",
    # "ok",
    # "not",
    # "mobile",
    # "middle",
    # "message",
    # "loyal",
    # "lounge",
    # "looks",
    # "longer",
    # "lauren",
    # "landed",
    # "hung",
    # "huge",
    # "hrs",
    # "hoping",
    # "holding",
    # "him",
    # "help",
    # "help",
    # "great",
    # "got",
    # "gate",
    # "gate",
    # "following",
    # "favorite",
    # "fail",
    # "excited",
    # "excellent",
    # "ever",
    # "don't",
    # "did",
    # "desk",
    # "dca",
    # "date",
    # "currently",
    # "course",
    # "could",
    # "completely",
    # "code",
    # "club",
    # "club",
    # "card",
    # "busy",
    # "both",
    # "air",
    # "ago"
]

lista_politics = [
    "a",
    "e",
    "i",
    "o",
    "u",
    "s",
    "the",
    "to",
    ":(",
    "of",
    "and",
    "in",
    ":)",
    "is",
    "for",
    "you",
    "that",
    "it",
    "with",
    "my",
    "will",
    "on",
    "was",
    "this",
    "i'm",
    "are",
    "not",
    "me",
    "but",
    "have",
    "be",
    "at",
    "says",
    "from",
    "so",
    "who",
    "url",
    ":d",
    "he",
    "gt",
    "do",
    "like",
    "just",
    "don't",
    "about",
    "more",
    "by",
    "know",
    "there",
    "even",
    "because",
    "want",
    "people",
    "what",
    "if",
    "has",
    "all",
    "haddad",
    "going",
    "-",
    "love",
    "can",
    "your",
    "day",
    "we",
    "very",
    "an",
    "already",
    "see",
    "the",
    "go",
    "support",
    "up",
    "really",
    "no",
    "it's",
    "after",
    "good",
    "think",
    "as",
    "only",
    "wanted",
    "out",
    "or",
    "they",
    "here",
    "when",
    ":))",
    "sad",
    "eleições2018",
    "didn't",
    "vote",
    "round",
    "one",
    "would",
    "had",
    "today",
    "now",
    "how",
    "am",
    "too",
    "she",
    "take",
    "get",
    "much",
    "it",
    "against",
    "new",
    "his",
    "happy",
    "time",
    "than",
    "second",
    "little",
    "these",
    "first",
    "can't",
    "most",
    "our",
    "give",
    "pt",
    "children's",
    "were",
    "being",
    "still",
    "sp",
    "brazil",
    "my",
    "her",
    "good",
    "and",
    ":((",
    "those",
    "never",
    "make",
    "you",
    "say",
    "him",
    "everything",
    "doesn't",
    "always",
    "beautiful",
    "lot",
    "in",
    "also",
    "without",
    "hope",
    "bad",
    "need",
    "help",
    "miss",
    "thing",
    "best",
    "video",
    "did",
    "but",
    "try",
    #"talk",
    #"went",
    #"them",
    #"right",
    #"morning",
    #"how",
    #"2nd",
    #"said",
    #"their",
    #"life",
    #"left",
    #"end",
    #"paulo",
    #"over",
    #"other",
    #"which",
    #"happy",
    #"friend",
    #"years",
    #"world",
    #"we",
    #"-via",
    #"should",
    #"person",
    #"man",
    #"it's",
    #"i'll",
    #"then",
    #"someone",
    #"friends",
    #":-)",
    #":)))",
    #"wants",
    #"sorry",
    #"some",
    #"million",
    #"made",
    #"look",
    #"country",
    #"come",
    #"been",
    #"back",
    #"any",
    #"again",
    #"work",
    #"things",
    #"since",
    #"find",
    #"election",
    #"two",
    #"são",
    #"bar",
    #"announces",
    #"year",
    #"what",
    #"thanks",
    #"talking",
    #"leave",
    #"least",
    #"guys",
    #"could",
    #"us",
    #"next",
    #"holiday",
    #"heart",
    #"hate",
    #"everyone",
    #"every",
    #"elected",
    #"candidates",
    #"better",
    #"arrested",
    #"show",
    #"lost",
    #"i’m",
    #"government",
    #"does",
    #"came",
    #"unfortunately",
    #"political",
    #"money",
    #"death",
    #"baby",
    #"thought",
    #"shit",
    #"psdb",
    #"if",
    #"got",
    #"dream",
    #"doria",
    #"well",
    #"use",
    #"there",
    #"news",
    #"makes",
    #"free",
    #"feel",
    #"another",
    #"yesterday",
    #"where",
    #"until",
    #"this",
    #"school",
    #"put",
    #"live",
    #"it",
    #"days",
    #"candidate",
    #"angel",
    #"yes",
    #"why",
    #"way",
    #"send",
    #"same",
    #"myself",
    #"liked",
    #"having",
    #"anything",
    #"2018",
    #"when",
    #"thinking",
    #"old",
    #"last",
    #"family",
    #"don’t",
    #"children",
    #"call",
    #"understand",
    #"thank",
    #"something",
    #"saw",
    #"president",
    #"nothing",
    #"many",
    #"home",
    #"care",
    #"tse",
    #"stay",
    #"must",
    #"goes",
    #"god",
    #"feeling",
    #"class",
    #"children's",
    #"child",
    #"able",
    #"you",
    #"week",
    #"read",
    #"michael",
    #"may",
    #"fuck",
    #"alone",
    #"voters",
    #"us",
    #"url",
    #"see",
    #"post",
    #"let's",
    #"found",
    #"campaign",
    #"before",
    #"you're",
    #"woke",
    #"with",
    #"win",
    #"voted",
    #"thanks",
    #"thank",
    #"state",
    #"play",
    #"phone",
    #"off",
    #"me",
    #"https:",
    #"fake",
    #"do",
    #"decides",
    #"debate",
    #"comes",
    #"believe",
    #"almost",
    #"yes",
    #"woman",
    #"started",
    #"shows",
    #"saying",
    #"presidential",
    #"please",
    #"haven't",
    #"great",
    #"for",
    #"calls",
    #"brazilian",
    #"birthday",
    #"wish",
    #"through",
    #"rio",
    #"no",
    #"name",
    #"lunch",
    #"looks",
    #"let",
    #"just",
    #"into",
    #"guy",
    #"game",
    #"day",
    #"takes",
    #"son",
    #"so",
    #"roger",
    #"remember",
    #"month",
    #"mine",
    #"half",
    #"ever",
    #"elections",
    #"buy",
    #"asks",
    #"anymore",
    #"worse",
    #"won't",
    #"witzel",
    #"whole",
    #"waters",
    #"votes",
    #"they",
    #"oh",
    #"new",
    #"launches",
    #"frança",
    #"follow",
    #"#elections2018",
    #"attacks",
    #"anyone",
    #"ai",
    #"after",
    #":-(:",
    #":(((((",
    #"why",
    #"watch",
    #"tomorrow",
    #"that's",
    #"part",
    #"he",
    #"gets",
    #"face",
    #"don't",
    #"billion",
    #"away",
    #":(((",
    #"voting",
    #"used",
    #"trump",
    #"that",
    #"such",
    #"study",
    #"received",
    #"program",
    #"it’s",
    #"it",
    #"hurricane",
    #"god",
    #"fight",
    #"father",
    #"down",
    #"difficult",
    #"deputies",
    #"crying",
    #"cool",
    #"city",
    #"car",
    #"between",
    #"at",
    #"ask",
    #"young",
    #"while",
    #"took",
    #"three",
    #"tell",
    #"stop",
    #"social",
    #"sleep",
    #"series",
    #"rt",
    #"release",
    #"real",
    #"possible",
    #"photos",
    #"pf",
    #"pay",
    #"on",
    #"lt",
    #"looking",
    #"leaves",
    #"its",
    #"hair",
    #"haddad",
    #"fraud",
    #"economic",
    #"die",
    #"day",
    #"da",
    #"cute",
    #"congratulations",
    #":(:",
    #"wrong",
    #"whatsapp",
    #"trying",
    #"true",
    #"team",
    #"soon",
    #"return",
    #"place",
    #"own",
    #"making",
    #"keep",
    #"justice",
    #"increase",
    #"house",
    #"google",
    #"getting",
    #"fucking",
    #"former",
    #"florida",
    #"far",
    #"eat",
    #"doing",
    #"declares",
    #"debates",
    #"bro",
    #"afraid",
    #":))))",
    #"worst",
    #"won",
    #"women",
    #"welcome",
    #"releases",
    #"problem",
    #"photo",
    #"party",
    #"one",
    #"night",
    #"market",
    #"killed",
    #"hours",
    #"guedes",
    #"giving",
    #"girl",
    #"fine",
    #"electoral",
    #"dollar",
    #"deserve",
    #"de",
    #"called",
    #"arrived",
    #"around",
    #":((((",
    #"wave",
    #"usa",
    #"today",
    #"taking",
    #"season",
    #"proposals",
    #"people",
    #"open",
    #"master",
    #"i've",
    #"hug",
    #"hit",
    #"few",
    #"facebook",
    #"dead",
    #"cmg",
    #"choose",
    #"check",
    #"chamber",
    #"cannot",
    #"bought",
    #"both",
    #"bolsa",
    #"among",
    #"who",
    #"venezuela",
    #"together",
    #"today",
    #"times",
    #"thousand",
    #"that's",
    #"suspected",
    #"speech",
    #"situation",
    #"seen",
    #"seeing",
    #"scared",
    #"sad",
    #"respect",
    #"point",
    #"paes",
    #"ones",
    #"now",
    #"much",
    #"let's",
    #"less",
    #"journalist",
    #"imagine",
    #"happened",
    #"had",
    #"gift",
    #"fun",
    #"friend",
    #"explain",
    #"dog",
    #"deputy",
    #"couldn't",
    #"cell",
    #"big",
    #"bed",
    #"ago",
    #"account",
    #"well",
    #"watching",
    #"waiting",
    #"voter",
    #"via",
    #"unfortunately",
    #"type",
    #"tv",
    #"too",
    #"to",
    #"talks",
    #"suspicion",
    #"supports",
    #"street",
    #"start",
    #"speak",
    #"smile",
    #"seems",
    #"rises",
    #"pt",
    #"prison",
    #"politics",
    #"police",
    #"participate",
    #"pain",
    #"paid",
    #"nor",
    #"neither",
    #"mother",
    #"months",
    #"moment",
    #"military",
    #"me",
    #"long",
    #"life",
    #"job",
    #"is",
    #"interior",
    #"inside",
    #"important",
    #"imf",
    #"hell",
    #"head",
    #"gives",
    #"friday",
    #"ended",
    #"doesn’t",
    #"different",
    #"didn’t",
    #"cut",
    #"criticizes",
    #"closes",
    #"close",
    #"break",
    #"boy",
    #"become",
    #"ballot",
    #"asked",
    #"arrives",
    #"accused",
    #"accident",
    #"you",
    #"yet",
    #"wasn't",
    #"violence",
    #"un",
    #"told",
    #"themselves",
    #"sure",
    #"strength",
    #"store",
    #"sick",
    #"run",
    #"released",
    #"public",
    #"points",
    #"orders",
    #"opens",
    #"ngm",
    #"neutrality",
    #"music",
    #"man",
    #"luxury",
    #"lack",
    #"killer",
    #"judge",
    #"hits",
    #"health",
    #"happy",
    #"group",
    #"global",
    #"former",
    #"forget",
    #"fear",
    #"fans",
    #"falls",
    #"enjoy",
    #"each",
    #"during",
    #"dies",
    #"dear",
    #"company",
    #"coming",
    #"chance",
    #"brescia",
    #"boys",
    #"attack",
    #"angel",
    #"album",
    #"ah",
    #"1st",
    #"you're",
    #"you",
    #"world",
    #"wednesday",
    #"website",
    #"wait",
    #"visit",
    #"valid",
    #"united",
    #"tried",
    #"tired",
    #"there",
    #"taylor",
    #"super",
    #"story",
    #"skaf",
    #"selection",
    #"round",
    #"right",
    #"police",
    #"plans",
    #"plan",
    #"places",
    #"perillo",
    #"pension",
    #"pass",
    #"number",
    #"now",
    #"not",
    #"nobody",
    #"needs",
    #"names",
    #"mom",
    #"missing",
    #"loved",
    #"look",
    #"lol",
    #"know",
    #"kkkkk",
    #"kind",
    #"joão",
    #"james",
    #"investigation",
    #"internet",
    #"hi",
    #"helps",
    #"heard",
    #"governor",
    #"government",
    #"gave",
    #"future",
    #"four",
    #"flight",
    #"felt",
    #"evidence",
    #"escape",
    #"education",
    #"dictatorship",
    #"denies",
    #"cry",
    #"crazy",
    #"control",
    #"confirms",
    #"china",
    #"check",
    #"case",
    #"bus",
    #"block",
    #"blacks",
    #"biggest",
    #"badly",
    #"appears",
    #"advantage",
    #"accept",
    #"world",
    #"very",
    #"using",
    #"uses",
    #"upset",
    #"under",
]